<a href="https://colab.research.google.com/github/KwonYN/TIL/blob/master/PYTHON/TENSORFLOW/2%EB%B6%80_1%EA%B3%BC_AI%EB%A5%BC_%EC%9C%84%ED%95%9C_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter2-1. TensorFlow 기초 - AI를 위한 NumPy

## [1] Import NumPy

> ### Import NumPy

In [0]:
import numpy as np

print("NumPy Version : {}".format(np.__version__))

NumPy Version : 1.17.4


# List와 Array? 그리고 Dictionary

  ● List : 

    - 메모리에 선형적으로 저장이 되어 있기 때문에 Random Access ( ex. Arr[2] )로 접근 가능!

    - 하지만 삽입과 삭제가 많은 경우, 비효율적!

    - Squence List, Array List

       <-> Linked List : **삽입/삭제 시 효율적**이지만, **Random Access가 불편**함. 이를 위한 새로운 자료구조를 또 만들어야 하는 상황!


    - 앞으로 배울 List는 이 LinkedList에서 가지고 왔다고 생각하면 됨!


  ● Dictionary:

    - a = { 'b':5, ... }
      a['b']로 5값 찾을 수 있음. 여기에서 키값인 'b'는 Hashable.. 즉, **Hashtable**로 자료를 관리하는 것!!

## [2] Python vs NumPy

> ### Python

In [0]:
L = range(1000) # enumerate type이라고 함!

In [5]:
%timeit [i**2 for i in L] # ipynb파일에서 magic command의 일종! 연산의 시간을 재주는 모듈을 매직커맨드로!

1000 loops, best of 3: 247 µs per loop


>### NumPy

In [10]:
a = np.arange(1000) # 0 ~ 999가 저장. list로 보이겠지만, numpy.ndarray타입!!
print(type(a), a, sep='\n')

<class 'numpy.ndarray'>
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 24

In [12]:
%timeit a**2

The slowest run took 58.24 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.27 µs per loop


## [3] np.ndarray 생성 : np.array()

> ### 1-D Array

In [13]:
a = np.array([0, 1, 2, 3])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[0 1 2 3]
1
(4,)
4


> ### 2-D Array

In [17]:
b = np.array([[0, 1, 2, 3], [3, 4, 5]]) # 요소의 개수(?)가 이렇게 다르면, 2차원 array로 인식하는 것이 아니라 두 개의 다른 list가 들어있는 1차원 배열로!!
# array는 n행 m열 동일하게 요소 개수가 같아야 성립!!
print(b)
print(b.ndim)
print(b.shape)
print(len(b))
print(len(b[0]))

[list([0, 1, 2, 3]) list([3, 4, 5])]
1
(2,)
2
4


> ### 3-D Array

In [19]:
c = np.array([[[1], [2]], [[3], [4]]])
print(c)
print(c.ndim)
print(c.shape)
print(len(c))
print(len(c[0]))
print(len(c[0][0]))

[[[1]
  [2]]

 [[3]
  [4]]]
3
(2, 2, 1)
2
2
1


## [4] np.ndarray 생성하는 다른 함수들

> ### np.arange()

In [31]:
a = np.arange(10) # python의 range( start(inclusive), stop(exclusive), step(default=1) ) 와 똑같은 녀석!
print(a)

b = np.arange(1, 9, 2)  # 1 ~ 8까지 2steps 단위로 => 9미만의 홀수
print(b)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


>### np.linspace()

In [21]:
c = np.linspace(0, 1, 6)
# linearspace _ parameter/argument로 ( start(inclusive), stop(default=inclusive), step(data count), [optional : endpoint=False(endpoint exclusive)]) 
print(c)

d = np.linspace(0, 1, 5, endpoint=False)
# optional인 endpoint는 default가 True이고, 이는 즉 끝 숫자를 포함한다는 것. 빼주려면 False로 지정을 해주어야 함!
print(d)

[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]


>### np.ones(), np.zeros(), np.eye()

In [22]:
a = np.ones((3, 3))
print(a)

b = np.zeros((2, 2))
print(b)

c = np.eye(3)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


>### np.ones_like(), np.zeros_like(), np.empty_like()

In [23]:
a = [1,2,3,4]
a_like = np.ones_like(a)
print(a_like)

b = [[1,2,3],[4,5,6]]
b_like = np.zeros_like(b)
print(b_like)

c = [[1,2],[3,4]]
c_like = np.empty_like(c)
print(c_like)

[1 1 1 1]
[[0 0 0]
 [0 0 0]]
[[1 2]
 [3 4]]


## [5] Basic Data Type

>### np.ndarray.dtype

In [29]:
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 3.])
print(b.dtype)

c = np.array([1+2j, 3+4j, 5+6*1j])
print(c.dtype)

d = np.array([True, False, False, True])
print(d.dtype)

int64
float64
complex128
bool


>### array 생성 시 dtype 지정

In [30]:
e = np.array([1, 2, 3], dtype=float)
print(e)
print(e.dtype)

f = np.array([1., 2., 3.], dtype=int)
print(f)
print(f.dtype)

[1. 2. 3.]
float64
[1 2 3]
int64


## [6] Indexing & Slicing

> ### 기본 Indexing 방법

In [38]:
a = np.arange(10)
print(a)
print(a[0])
print(a[2])
print(a[-1])

b = np.eye(3)
print(b[0, 1])

[0 1 2 3 4 5 6 7 8 9]
0
2
9
0.0


>### Multidimensional array의 Indexing

In [44]:
a = np.eye(3)

print(a,'\n')
print(a[1, 1],'\n')

a[2, 1] = 10
print(a[2, 1],'\n')   # third line, second column

print(a,'\n')
print(a[1],'\n')
print(a[0:2])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

1.0 

10.0 

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. 10.  1.]] 

[0. 1. 0.] 

[[1. 0. 0.]
 [0. 1. 0.]]


>### Slicing

In [45]:
a = np.arange(10)

print(a,'\n')

print(a[2:9:3],'\n') # [start:end:step]

print(a[:4],'\n')

print(a[1:3],'\n')

print(a[::2],'\n')

print(a[3:],'\n')

[0 1 2 3 4 5 6 7 8 9] 

[2 5 8] 

[0 1 2 3] 

[1 2] 

[0 2 4 6 8] 

[3 4 5 6 7 8 9] 



In [55]:
a = np.arange(10)
print(a,'\n')
a[5:] = 10
print(a,'\n')

b = np.arange(5)
print(b,'\n')
a[5:] = b[::-1]
print(a,'\n') # 사이즈가 맞지 않으면 브로드케스트가 안된다는 에러!!!

[0 1 2 3 4 5 6 7 8 9] 

[ 0  1  2  3  4 10 10 10 10 10] 

[0 1 2 3 4] 

[0 1 2 3 4 4 3 2 1 0] 



## [7] Copies and views

>### 'b'의 정체?

In [60]:
a = np.arange(10)
print(a)
b = a[::2]
print(b)

print(np.may_share_memory(a, b))

b[0] = 12
print(b)
print(a)

print(np.may_share_memory(a, b))

print(b.base) # a배열의 내용이 출력됨!! ohoh~~

print(a.strides)  # byte단위로 결과값이 나옴!! 8 == int64
print(b.strides)  # a배열을 2칸 단위로 건너뛰고 있으므로 16 byte = int64 2개 단위


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]
True
[12  1  2  3  4  5  6  7  8  9]
(8,)
(16,)


>### 강제 Copy 만들기

In [68]:
a = np.arange(10)
c = a[::2].copy()
      # np.ndarray타입의 메서드인 copy() 메서드!!
print(type(a))

print(a)
print(c)

c[0] = 12
print(a)

print(np.may_share_memory(a, c))


<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
False


## [8] Elementwise operation

> ### Scalar value와 Array 사이의  연산

In [69]:
# p.44 : a배열의 모든 요소와 스칼라값인 1이 한꺼번에 같이 연산이 됨!
a = np.array([1, 2, 3, 4])
print(a + 1)
print(2 ** a)

[2 3 4 5]
[ 2  4  8 16]


>### Array와 Array 사이의 연산

In [72]:
b = np.ones(4) + 1

print(a - b)
print(a * b)

j = np.arange(5)
print(2**(j + 1) - j)

[-1.  0.  1.  2.]
[2. 4. 6. 8.]
[ 2  3  6 13 28]


>### c * c => Matrix Multiplication?

In [92]:
c = np.ones((3, 3))+1
print(c * c)

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


>### Matrix Multiplication : np.dot

In [80]:
mat_mul = np.dot(c,c)
print(mat_mul)

[[12. 12. 12.]
 [12. 12. 12.]
 [12. 12. 12.]]


>### Element-wise 비교

In [85]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = a == b
d = (a == b)[0]

print(c, d)
print(a == b)
print(a > b)

[False  True False  True] False
[False  True False  True]
[False False  True False]


>### Element-wise 논리연산

In [86]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a, b))
print(a|b)

print(np.logical_and(a, b))
print(a&b)

[ True  True  True False]
[ True  True  True False]
[ True False False False]
[ True False False False]


>### Element-wise 연산에서 operand들의 shape mismatche

In [88]:
a = np.arange(4)
print(np.array([1, 2]))
a + np.array([1, 2])  

[1 2]


ValueError: ignored

## [9] Dimension reduction 연산

>### np.sum(), np.ndarray.sum()

In [93]:
x = np.array([1, 2, 3, 4])
print(type([1, 2, 3, 4]), type(x))

print(np.sum(x))
print(x.sum())  # 1차원 배열의 값을 하나의 스칼라 값으로 Dimension Reduction해준 것!

<class 'list'> <class 'numpy.ndarray'>
10
10


>### 특정 축을 기준으로 합계 구하기

In [96]:
# p.47
x = np.array([[1, 1, 5, 6, 8, 7], [2, 2, 9, 7, 0, 5]])

print(x.sum(axis=0))  # axis=0은 우리가 생각하는 열 기준(같은 열의 합) -> 1열의 합, 2열의 합, 3열의 합. ...

print(x.sum(axis=1))  # axis=1은 우리가 생각하는 행 기준(같은 행의 합) -> 1행의 합, 2행의 합, 3행의 합, ...

[ 3  3 14 13  8 12]
[28 25]


>### np.ndarray.min(), np.ndarray.max(), np.ndarray.argmin(), np.ndarray.argmax() 

In [97]:
# p.48
x = np.array([1, 1, 1, 4, 3, 2, 4])

print(x.min())
print(x.max())

print(x.argmin()) # 최소값/최대값 중 가장 앞에 있은 인덱스를 찾아서 리턴!!
print(x.argmax())

1
4
0
3


In [98]:
# p.48
x = np.array([[9,2,10,6,1],[5,7,3,4,8]])

print(x.argmin(axis=0))
print(x.argmax(axis=1))

[1 0 1 1 0]
[2 4]


>### np.all(), np.any()

In [99]:
# p.49
print(np.all([True, True, False]))
print(np.any([True, True, False]))

False
True


>### 통계 관련

In [101]:
# p.49
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

print(type(x.mean()), x.mean())

print(np.median(x))
print(np.median(y, axis=-1))

print(x.std())

<class 'numpy.float64'> 1.75
1.5
[2. 5.]
0.82915619758885


## [10] Broadcasting

>### 결과 출력용 함수

In [0]:
def Print_ABC(a, b, c):
    print("{}, a.shape = {}".format(a, a.shape))
    print("{}, b.shape = {}".format(b, b.shape))
    print("{}, c.shape = {}".format(c, c.shape))    

>### array + scalar

In [103]:
a = np.array([1, 2, 3])
b = 2
c = a + b

Print_ABC(a, np.array(b), c)

[1 2 3], a.shape = (3,)
2, b.shape = ()
[3 4 5], c.shape = (3,)


>### array + array ex1

In [0]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([1, 2, 3])
c = a + b

Print_ABC(a, b, c)

>### array + array ex2

In [110]:
a = np.array([1, 2, 3, 4])
b = np.array([[1], [2]])
c = a + b

Print_ABC(a, b, c)


# p.52
# 하지만 이 둘은 이미 차원이 똑같기 때문에, 차원을 확장하여 연산 X
# 사이즈를 맞추는 것에 앞서, 차원이 달라야 함!!
# 차원이 다른 두 값 사이에서 차원을 변경하여 값을 동일하게 맞출 수 있다면, Broadcasting Rule에 의해 연산 가능!!!!
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])
c = a+b
Print_ABC(a, b, c)


[1 2 3 4], a.shape = (4,)
[[1]
 [2]], b.shape = (2, 1)
[[2 3 4 5]
 [3 4 5 6]], c.shape = (2, 4)


ValueError: ignored

>### array + array ex3

In [111]:
a = np.array([[1], [2], [3], [4]])
b = np.array([1, 2, 3])
c = a + b

Print_ABC(a, b, c)

[[1]
 [2]
 [3]
 [4]], a.shape = (4, 1)
[1 2 3], b.shape = (3,)
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]], c.shape = (4, 3)


## [11] Array Manipulation

>### Flattening : np.ndarry.ravel()

In [112]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.ravel())

[1 2 3 4 5 6]


>### Reshaping : np.ndarray.reshape
#### ndarray.reshape may return a view (cf help(np.reshape))), or copy

In [116]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.reshape((6, 1))
print(b)

c = a.reshape((3, 2))
print(c)

print(a.reshape((-1,))) # Flattening!!

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]
[1 3 5 1 5 5 5 9 1 5 3 1]


In [114]:
a.reshape((2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

>### Transpose

In [126]:
# p.54
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.transpose())  # .transpose() 라는 메서드!
print(a)  # a의 내용이 바뀔까? Nope! 바뀌지 않음!! a.transpose()으로 인해 축 방향이 변경된 결과값이 "리턴"되는 것!
print(a.T)            # 2차원 배열 입장에서 .T는 a의 transpose 결과를 가지고 있다고 생각하라...


b = a.transpose()       # 여기에서는 View라고 나옴. 하지만 상황에 따라 달라질 수도 있다고... 근데 view라고 알고 있자!!!
print(np.may_share_memory(a, b))
b[2, 1] = 50
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
True
[[ 1  2  3]
 [ 4  5 50]
 [ 7  8  9]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3 50  9]]


> ### Dimension shuffling

In [132]:
# p. 56 : 이 부분 조금 헷갈리면서 어려움. 다시 볼 것!
a = np.arange(4*3*2).reshape((4, 3, 2))+1

print(a[0, 2, 1])
print(a)
print(a.shape)

b = a.transpose((1, 2, 0))
print(b.shape)
print(b[2, 1, 0])
print(b)
print(b.shape)



6
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
(4, 3, 2)
(3, 2, 4)
6
[[[ 1  7 13 19]
  [ 2  8 14 20]]

 [[ 3  9 15 21]
  [ 4 10 16 22]]

 [[ 5 11 17 23]
  [ 6 12 18 24]]]
(3, 2, 4)
