<a href="https://colab.research.google.com/github/KwonYN/TIL/blob/master/PYTHON/TENSORFLOW/2%EB%B6%80_3%EA%B3%BC_Constant_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter2. TensorFlow 기초

 ## 2-3 Constant, Variable

> ### Import TensorFlow

In [1]:
%tensorflow_version 1.x

import numpy as np
import tensorflow as tf

print("NumPy Version : {}".format(np.__version__))
print("TensorFlow Version : {}".format(tf.__version__))

NumPy Version : 1.17.4
TensorFlow Version : 1.15.0


> ### [예제 1] tf.constant()로 Tensor 생성

In [13]:
c_int = tf.constant(3)
c_float1 = tf.constant(1.239)
c_float2 = tf.constant(3, dtype= tf.float32 )
c_str = tf.constant("Hello, TensorFlow", name= 'Const_String')
c_str1 = tf.constant("Hello, TensorFlow", name= 'Const_String')
# c_float3 = tf.constant(1.239, dtype= tf.int32) # TypeError

list_constant = [c_int, c_float1, c_float2, c_str, c_str1]

with tf.Session() as sess:
  for tensor in list_constant:
    result = sess.run(tensor)
    print(tensor,"value = {}".format(result))

Tensor("Const_33:0", shape=(), dtype=int32) value = 3
Tensor("Const_34:0", shape=(), dtype=float32) value = 1.2389999628067017
Tensor("Const_35:0", shape=(), dtype=float32) value = 3.0
Tensor("Const_String_18:0", shape=(), dtype=string) value = b'Hello, TensorFlow'
Tensor("Const_String_19:0", shape=(), dtype=string) value = b'Hello, TensorFlow'


> ### [예제 2] 각 type별 표현 범위

In [15]:
def Print_TF_Type(title, list_types):
  print("< {} >".format(title))
  [print("{:10} : {} ~ {}".format(t.name, t.min , t.max)) for t in list_types]
  print()

list_types_float = [tf.float16, tf.float32, tf.float64]
list_types_bfloat = [tf.bfloat16]
list_types_int = [tf.int8, tf.int16, tf.int32, tf.int64]
list_types_uint = [tf.uint8, tf.uint16, tf.uint32, tf.uint64]

Print_TF_Type("Min,Max of tf.float[16,32,64]",list_types_float)
Print_TF_Type("Min,Max of tf.bfloat16",list_types_bfloat)
Print_TF_Type("Min,Max of tf.int[8,16,32,64]",list_types_int)
Print_TF_Type("Min,Max of tf.uint[8,16,32,64]",list_types_uint)

< Min,Max of tf.float[16,32,64] >
float16    : -65504.0 ~ 65504.0
float32    : -3.4028234663852886e+38 ~ 3.4028234663852886e+38
float64    : -1.7976931348623157e+308 ~ 1.7976931348623157e+308

< Min,Max of tf.bfloat16 >
bfloat16   : -3.38953139e+38 ~ 3.38953139e+38

< Min,Max of tf.int[8,16,32,64] >
int8       : -128 ~ 127
int16      : -32768 ~ 32767
int32      : -2147483648 ~ 2147483647
int64      : -9223372036854775808 ~ 9223372036854775807

< Min,Max of tf.uint[8,16,32,64] >
uint8      : 0 ~ 255
uint16     : 0 ~ 65535
uint32     : 0 ~ 4294967295
uint64     : 0 ~ 18446744073709551615



> ### [예제 3] Rank 0 : Scalar, Magnitude

In [16]:
SC_int = tf.constant(451, dtype= tf.int16, name= 'Const1')
SC_float = tf.constant(3.14159265359, name= 'Const2')
SC_string = tf.constant("Elephant", name= 'Const3')

list_SC = [SC_int, SC_float, SC_string]

print("SC_int.shape = {}".format(SC_int.shape))

with tf.Session() as sess:
  for tensor in list_SC:
    rank, result = sess.run([tf.rank(tensor), tensor])
    print("Rank = {}, {}, Result = {}".format(rank, tensor, result))

SC_int.shape = ()
Rank = 0, Tensor("Const1:0", shape=(), dtype=int16), Result = 451
Rank = 0, Tensor("Const2:0", shape=(), dtype=float32), Result = 3.1415927410125732
Rank = 0, Tensor("Const3:0", shape=(), dtype=string), Result = b'Elephant'


> ### [예제 4] Rank 1 : Vector

In [17]:
VT_int1 = tf.constant([10, 3], name= 'Const1')
VT_int2 = tf.constant([1], name= 'Const2')
VT_floats = tf.constant([3.1415, 10.23], name= 'Const3')
VT_strings = tf.constant(["Elephant", "Rabbit", "Turtle"], name= 'Const4')

list_VT = [VT_int1, VT_int2, VT_floats, VT_strings]

with tf.Session() as sess:
  for tensor in list_VT:
    rank, result = sess.run([tf.rank(tensor), tensor])
    print("Rank = {}, {}, Result = {}".format(rank, tensor, result))

Rank = 1, Tensor("Const1_1:0", shape=(2,), dtype=int32), Result = [10  3]
Rank = 1, Tensor("Const2_1:0", shape=(1,), dtype=int32), Result = [1]
Rank = 1, Tensor("Const3_1:0", shape=(2,), dtype=float32), Result = [ 3.1415 10.23  ]
Rank = 1, Tensor("Const4:0", shape=(3,), dtype=string), Result = [b'Elephant' b'Rabbit' b'Turtle']


> ### [예제 5] Rank 2 : Matrix

In [18]:
MT_int1 = tf.constant([[10, 3], [4, 5]], name= 'Const1')
MT_int2 = tf.constant([[1]], name= 'Const2')
MT_floats = tf.constant([[3.1415, 10.23, 9.], [2.3, 11, 15.0]], name= 'Const3')

list_MT = [MT_int1, MT_int2, MT_floats]

with tf.Session() as sess:
  for tensor in list_MT:
    rank, result = sess.run([tf.rank(tensor), tensor])
    print("Rank = {}, {},\n{}".format(rank, tensor, result))

Rank = 2, Tensor("Const1_2:0", shape=(2, 2), dtype=int32),
[[10  3]
 [ 4  5]]
Rank = 2, Tensor("Const2_2:0", shape=(1, 1), dtype=int32),
[[1]]
Rank = 2, Tensor("Const3_2:0", shape=(2, 3), dtype=float32),
[[ 3.1415 10.23    9.    ]
 [ 2.3    11.     15.    ]]


> ### 아래 코드의 결과는?

In [31]:
# value ( shape가 (2, 2)인 )와 shape이 다름 => 그런데 verify_shape=True이므로 'TypeError' 메시지가 뜰 것!
MT_int2 = tf.constant([[1, 2], [4, 5]], shape= (4, 3), verify_shape= True)  # 실행 시, False로 바꾸거나 주석 처리

# 딱히 문제로 삼지를 않네...? 그리고 찍어봐됴 shape이 (4, 3)이라고 나옴..
MT_int3 = tf.constant([[1, 2], [4, 5]], shape= (4, 3), verify_shape= False)

list_MT = [MT_int2, MT_int3]

with tf.Session() as sess:
  for tensor in list_MT:
    rank, result = sess.run([tf.rank(tensor), tensor])
    print("Rank = {}, {},\n{}".format(rank, tensor, result))

## 프린트해보면, 가장 마지막 값으로 쭈우우우욱 설정된 것을 볼 수 있음 -> shape는 일반적으로 딱히 건들지는 않는다고 함...
## 하지만 과정에서 내가 실수했을 수도 있으니 디버깅 차원에서 shape를 직접 값으로 주고, verify_shape=True를 해줌으로써 실수 줄일 수 있다고 함!!

Rank = 2, Tensor("Const_44:0", shape=(4, 3), dtype=int32),
[[1 2 4]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
Rank = 2, Tensor("Const_45:0", shape=(4, 3), dtype=int32),
[[1 2 4]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


> ### [예제 6] Rank 3 : Cube

In [32]:
CB_int1 = tf.constant([[[1, 2], [3, 4]],[[5, 6], [7, 8]]], name= 'Const1')
CB_int2 = tf.constant([[[100]]], name= 'Const2')
CB_floats = tf.constant([[[3.1415, 10.23, 9.], [2.3, 11, 15.0]]], name= 'Const3')

list_CB = [CB_int1, CB_int2, CB_floats]

with tf.Session() as sess:
  for tensor in list_CB:
    rank, result = sess.run([tf.rank(tensor), tensor])
    print("Rank = {}, {}, \nResult : \n{}".format(rank, tensor, result))

Rank = 3, Tensor("Const1_3:0", shape=(2, 2, 2), dtype=int32), 
Result : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Rank = 3, Tensor("Const2_3:0", shape=(1, 1, 1), dtype=int32), 
Result : 
[[[100]]]
Rank = 3, Tensor("Const3_3:0", shape=(1, 2, 3), dtype=float32), 
Result : 
[[[ 3.1415 10.23    9.    ]
  [ 2.3    11.     15.    ]]]


> ### [예제 7] Higher rank of Tensor

In [33]:
batch_images = tf.constant(0 , shape =(10, 240, 320, 3))

with tf.Session() as sess:
    rank = sess.run(tf.rank(batch_images))
    print("Rank = {}, {}".format(rank, batch_images))

Rank = 4, Tensor("Const_46:0", shape=(10, 240, 320, 3), dtype=int32)


> ### [예제 8] Create Variable and Variable Initializer

In [38]:
# 예제 2-3-9
# Variable (Initializer 실행)

# Error : p.78
v1 = tf.Variable(10)  # 근데 이렇게 하면 초기화 되는 것 아님...?
# 그런데 Runtime에도 v1은 10이라는 값과 타입을 가지고 있는 상황이 아니라고 하는데..!!
# => Runtime에 지정해준 값을 사용하게끔 하고 싶다면? 처음에 "initialize"를 의무적으로 해야 한다고 함!! 그래야 그 값들을 사용해서 연산에 사용하든 할 수 있다고!!

with tf.Session() as sess:
    #sess.run(tf.global_variables_initializer()) # ~ Initializer : 변수에 실제 값을 매칭(?)시켜주는 역할을 한다고 함! 이래야 변수가 값을 가질 수 있음!!
    print("v1 = {}".format(v1))
    result = sess.run(v1)
    print("value = {}".format(result))

v1 = <tf.Variable 'Variable_4:0' shape=() dtype=int32_ref>


FailedPreconditionError: ignored

In [36]:
  # 정상동작 : p.78
  v1 = tf.Variable(10)
  global_init = tf.global_variables_initializer() # tf.global_variables_initializer()의 리턴은 '텐서!!'

  with tf.Session() as sess:
      sess.run(global_init) # Variable Initializer
      print("v1 = {}".format(v1))
      result = sess.run(v1)
      print("value = {}".format(result))

v1 = <tf.Variable 'Variable_2:0' shape=() dtype=int32_ref>
value = 10


> ### [예제 9] 상수 초기값을 가진 변수

In [39]:
var_1 = tf.Variable(10)
var_2 = tf.Variable(20, dtype= tf.float64)
var_3 = tf.Variable(30, name= 'VAR_Weight')

initializer = tf.global_variables_initializer()
list_var = [var_1, var_2, var_3]

with tf.Session() as sess:
  sess.run(initializer)
  for var in list_var:
    result = sess.run(var)
    print("Var = {}".format(var))
    print("Value = {}".format(result))

Var = <tf.Variable 'Variable_5:0' shape=() dtype=int32_ref>
Value = 10
Var = <tf.Variable 'Variable_6:0' shape=() dtype=float64_ref>
Value = 20.0
Var = <tf.Variable 'VAR_Weight:0' shape=() dtype=int32_ref>
Value = 30


> ### [예제 10] 특정 함수에 의해 만들어진 초기값을 사용하는 변수

In [40]:
var_1 = tf.Variable(tf.zeros((2,3)))
var_2 = tf.Variable(tf.ones((1,5)))
var_3 = tf.Variable(tf.eye(2,2), name= 'VAR_Weight')

initializer = tf.global_variables_initializer()
list_var = [var_1, var_2, var_3]

with tf.Session() as sess:
  sess.run(initializer)
  for var in list_var:
    result = sess.run(var)
    print("Var = {}".format(var))
    print("Value =\n{}".format(result))

Var = <tf.Variable 'Variable_7:0' shape=(2, 3) dtype=float32_ref>
Value =
[[0. 0. 0.]
 [0. 0. 0.]]
Var = <tf.Variable 'Variable_8:0' shape=(1, 5) dtype=float32_ref>
Value =
[[1. 1. 1. 1. 1.]]
Var = <tf.Variable 'VAR_Weight_1:0' shape=(2, 2) dtype=float32_ref>
Value =
[[1. 0.]
 [0. 1.]]


> ### [예제 11] Random 함수에 의해 만들어진 초기값을 사용하는 변수

In [41]:
var_1 = tf.Variable(tf.random_normal((1,1)))
var_2 = tf.Variable(tf.truncated_normal((1,5), mean = 10, stddev = 0.1))
var_3 = tf.Variable(tf.random_uniform((2,2), minval=6, maxval=10))

initializer = tf.global_variables_initializer()
list_var = [var_1, var_2, var_3]

with tf.Session() as sess:
  sess.run(initializer)
  for var in list_var:
    result = sess.run(var)
    print("Var = {}".format(var))
    print("Value =\n{}".format(result))    

Var = <tf.Variable 'Variable_9:0' shape=(1, 1) dtype=float32_ref>
Value =
[[-0.8811088]]
Var = <tf.Variable 'Variable_10:0' shape=(1, 5) dtype=float32_ref>
Value =
[[10.097735  9.957455  9.818626  9.885069  9.958148]]
Var = <tf.Variable 'Variable_11:0' shape=(2, 2) dtype=float32_ref>
Value =
[[8.646751 8.48964 ]
 [9.437837 7.602503]]
