<a href="https://colab.research.google.com/github/KwonYN/TIL/blob/master/PYTHON/TENSORFLOW/Ch4_%EC%98%88%EC%A0%9C_01_04_2D_Convolution_Pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter4-2. CNN 기본연산

> ### Load Module

In [1]:
%tensorflow_version 1.x

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

print("Module Loaded.")
print("NumPy Version :{}".format(np.__version__))
print("TensorFlow Version :{}".format(tf.__version__))
print("Matplotlib Version :{}".format(plt.matplotlib.__version__))

Module Loaded.
NumPy Version :1.17.4
TensorFlow Version :1.15.0
Matplotlib Version :3.1.2


In [29]:
def Print_Array(np_array:np.ndarray, title:str)->None:
  print("Shape of {} : {}".format(title,np_array.shape))
  print(np_array)


6272


## [예제1] 2D Convolution

> ### [ Shape 정보 ]
> ### Input, Output Shape => NHWC format
> ### Filter Shape => [filter_height, filter_width, in_channels, out_channels]

> ### [Conv Exam1] Input shape = (1,5,5,1), Filter = (2,2,1,1)`

In [12]:
print("[Conv Exam1] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)")

#          np.arange(start, stop, step, dtype순!!)
np_input = np.arange(1,26,1,dtype=np.float32).reshape((1,5,5,1))
# 1, 2, 3, ..., 25 -> reshape to=( batch=1, height=5, width=5, channel=1 )

np_filter = np.array([1,1,1,1],dtype=np.float32).reshape((2,2,1,1))
# [1, 1, 1, 1]인 1차원 list를 shape( filter_height=2, width=2, input_channel_cnt=1, filter_cnt=1 )

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)
print("input_constant = {}, filter_constant = {}".format(input_constant, filter_constant))

print('------------------------------------------------------------------------------------')
# conv의 타입은 input인 np_input과 동일한 data_format Tensor일 것! =? input이 NHWC라면, conv 또한 NHWC
conv = tf.nn.conv2d(input_constant, filter=filter_constant, padding="VALID")
print(np_input.shape, conv.shape)

with tf.Session() as sess:
  out = sess.run(conv)

Print_Array(out, "Output")
Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")

[Conv Exam1] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)
input_constant = Tensor("Const_16:0", shape=(1, 5, 5, 1), dtype=float32), filter_constant = Tensor("Const_17:0", shape=(2, 2, 1, 1), dtype=float32)
------------------------------------------------------------------------------------
(1, 5, 5, 1) (1, 4, 4, 1)
Shape of Output : (1, 4, 4, 1)
[[[[16.]
   [20.]
   [24.]
   [28.]]

  [[36.]
   [40.]
   [44.]
   [48.]]

  [[56.]
   [60.]
   [64.]
   [68.]]

  [[76.]
   [80.]
   [84.]
   [88.]]]]
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Filter : (2, 2, 1, 1)
[[[[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]]]


> ### [Conv Exam2] Input shape = (1,5,5,3), Filter = (2,2,3,1)

In [17]:
print("[Conv Exam2] Input shape = (1,5,5,3), Filter = (2,2,3,1)")

np_input = np.arange(1,76,1,dtype=np.float32).reshape((1,5,5,3))
np_filter = np.array([1]*12,dtype=np.float32).reshape((2,2,3,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

print('------------------------------------------------------------------------')
conv = tf.nn.conv2d(input_constant, filter=filter_constant, padding="VALID")
print(conv.shape)

sess = tf.Session()
with tf.Session() as sess:
  out = sess.run(conv)

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")

[Conv Exam2] Input shape = (1,5,5,3), Filter = (2,2,3,1)
------------------------------------------------------------------------
(1, 4, 4, 1)
Shape of Input : (1, 5, 5, 3)
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]
   [ 7.  8.  9.]
   [10. 11. 12.]
   [13. 14. 15.]]

  [[16. 17. 18.]
   [19. 20. 21.]
   [22. 23. 24.]
   [25. 26. 27.]
   [28. 29. 30.]]

  [[31. 32. 33.]
   [34. 35. 36.]
   [37. 38. 39.]
   [40. 41. 42.]
   [43. 44. 45.]]

  [[46. 47. 48.]
   [49. 50. 51.]
   [52. 53. 54.]
   [55. 56. 57.]
   [58. 59. 60.]]

  [[61. 62. 63.]
   [64. 65. 66.]
   [67. 68. 69.]
   [70. 71. 72.]
   [73. 74. 75.]]]]
Shape of Filter : (2, 2, 3, 1)
[[[[1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]]]]
Shape of Output : (1, 4, 4, 1)
[[[[132.]
   [168.]
   [204.]
   [240.]]

  [[312.]
   [348.]
   [384.]
   [420.]]

  [[492.]
   [528.]
   [564.]
   [600.]]

  [[672.]
   [708.]
   [744.]
   [780.]]]]


> ### [Conv Exam3] Input shape = (1,5,5,3), Filter = (2,2,3,6)

In [16]:
print("[Conv Exam3] Input shape = (1,5,5,3), Filter = (2,2,3,6)")

np_input = np.arange(1,76,1,dtype=np.float32).reshape((1,5,5,3))
                                            # shape = "NWHC" format = (batch=1, height=5, width=5, channel=3)
np_filter = np.array([1]*2*2*3*6,dtype=np.float32).reshape((2,2,3,6))
# 1 channel 당 2by2 배열 * 3 channel * 6개 filter   # filter shape = (height=2, width=2, input channel=3, output channel=6)

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)
print(input_constant, np_filter, sep='\n')

print('------------------------------------------------------------------------')
conv = tf.nn.conv2d(input_constant, filter=filter_constant, padding="VALID")
print(conv.shape)

sess = tf.Session()
with tf.Session() as sess:
  out = sess.run(conv)

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")

[Conv Exam3] Input shape = (1,5,5,3), Filter = (2,2,3,6)
Tensor("Const_24:0", shape=(1, 5, 5, 3), dtype=float32)
[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]]
------------------------------------------------------------------------
(1, 4, 4, 6)
Shape of Input : (1, 5, 5, 3)
[[[[ 1.  2.  3.]
   [ 4.  5.  6.]
   [ 7.  8.  9.]
   [10. 11. 12.]
   [13. 14. 15.]]

  [[16. 17. 18.]
   [19. 20. 21.]
   [22. 23. 24.]
   [25. 26. 27.]
   [28. 29. 30.]]

  [[31. 32. 33.]
   [34. 35. 36.]
   [37. 38. 39.]
   [40. 41. 42.]
   [43. 44. 45.]]

  [[46. 47. 48.]
   [49. 50. 51.]
   [52. 53. 54.]
   [55. 56. 57.]
   [58. 59. 60.]]

  [[61. 62. 63.]
   [64. 65. 66.]
   [67. 68. 69.]
   [70. 71. 72.]
   [73. 74. 75.]]]]
Shape of Filter : (2, 2, 3, 6)
[[[[1. 1. 1. 1. 1

## [예제2] 2D Convolution : Padding

>### [Conv-Padding Exam] Input shape(NHWC) = (1,5,5,1), Filter = (3,3,1,1)

In [22]:
print("[Conv-Padding Exam] Input shape(NHWC) = (1,5,5,1), Filter = (3,3,1,1)")

np_input = np.arange(1,26,1,dtype=np.float32).reshape((1,5,5,1))
np_filter = np.array([1]*9,dtype=np.float32).reshape((3,3,1,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

print("-------------------------------------------------------------------------------")
conv = tf.nn.conv2d(input_constant, filter=filter_constant, padding="VALID")
conv_padding = tf.nn.conv2d(input_constant, filter=filter_constant, padding="SAME")
print("conv.shape = {}, conv_padding.shape = {}".format(conv.shape, conv_padding.shape))

with tf.Session() as sess:
  out,out_padding = sess.run((conv, conv_padding))

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output")
Print_Array(out_padding, "Output with Zero Padding")

[Conv-Padding Exam] Input shape(NHWC) = (1,5,5,1), Filter = (3,3,1,1)
-------------------------------------------------------------------------------
conv.shape = (1, 3, 3, 1), conv_padding.shape = (1, 5, 5, 1)
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Filter : (3, 3, 1, 1)
[[[[1.]]

  [[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]

  [[1.]]]]
Shape of Output : (1, 3, 3, 1)
[[[[ 63.]
   [ 72.]
   [ 81.]]

  [[108.]
   [117.]
   [126.]]

  [[153.]
   [162.]
   [171.]]]]
Shape of Output with Zero Padding : (1, 5, 5, 1)
[[[[ 16.]
   [ 27.]
   [ 33.]
   [ 39.]
   [ 28.]]

  [[ 39.]
   [ 63.]
   [ 72.]
   [ 81.]
   [ 57.]]

  [[ 69.]
   [108.]
   [117.]
   [126.]
   [ 87.]]

  [[ 99.]
   [153.]
   [162.]
   [171.]
   [117.]]

  [[ 76.]
  

## [예제3] 2D Convolution : Stride

>### [Conv - Stride  Exam] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1), stride 1

In [23]:
print("[Conv - Stride  Exam] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)")

np_input = np.arange(1,26,1,dtype=np.float32).reshape((1,5,5,1))
np_filter = np.array([1,1,1,1],dtype=np.float32).reshape((2,2,1,1))

input_constant = tf.constant(np_input)
filter_constant = tf.constant(np_filter)

conv = tf.nn.conv2d(input_constant, filter=filter_constant, padding="VALID")
conv_stride_2 = tf.nn.conv2d(input_constant, filter=filter_constant, strides=2,padding="VALID")

with tf.Session() as sess:
  out, out_stride2 = sess.run((conv,conv_stride_2))

Print_Array(np_input, "Input")
Print_Array(np_filter, "Filter")
Print_Array(out, "Output with Stride = None")
Print_Array(out_stride2, "Output with Stride = 2")

[Conv - Stride  Exam] Input shape(NHWC) = (1,5,5,1), Filter = (2,2,1,1)
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Filter : (2, 2, 1, 1)
[[[[1.]]

  [[1.]]]


 [[[1.]]

  [[1.]]]]
Shape of Output with Stride = None : (1, 4, 4, 1)
[[[[16.]
   [20.]
   [24.]
   [28.]]

  [[36.]
   [40.]
   [44.]
   [48.]]

  [[56.]
   [60.]
   [64.]
   [68.]]

  [[76.]
   [80.]
   [84.]
   [88.]]]]
Shape of Output with Stride = 2 : (1, 2, 2, 1)
[[[[16.]
   [24.]]

  [[56.]
   [64.]]]]


## [예제4] Pooling : Max Pooling

> ### [Pooling Exam1] Input shape(NHWC) = (1,4,4,1), ksize = 2, strides = 2

In [28]:
print("[Pooling Exam1] Input shape(NHWC) = (1,4,4,1), ksize = 2, strides = 2")

np_input = np.array([[1,5,6,2,9],[3,2,3,1,7],[15,0,4,1,6],[3,2,3,5,3],[3,3,5,5,3]],dtype=np.float32).reshape(1,5,5,1)

input_constant = tf.constant(np_input)

pool = tf.nn.max_pool2d(input_constant,ksize=2,strides=3,padding="VALID")

with tf.Session() as sess:
  out = sess.run(pool)

Print_Array(np_input, "Input")
Print_Array(out, "Output")

[Pooling Exam1] Input shape(NHWC) = (1,4,4,1), ksize = 2, strides = 2
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 5.]
   [ 6.]
   [ 2.]
   [ 9.]]

  [[ 3.]
   [ 2.]
   [ 3.]
   [ 1.]
   [ 7.]]

  [[15.]
   [ 0.]
   [ 4.]
   [ 1.]
   [ 6.]]

  [[ 3.]
   [ 2.]
   [ 3.]
   [ 5.]
   [ 3.]]

  [[ 3.]
   [ 3.]
   [ 5.]
   [ 5.]
   [ 3.]]]]
Shape of Output : (1, 2, 2, 1)
[[[[5.]
   [9.]]

  [[3.]
   [5.]]]]


> ### [Pooling Exam2] Input shape(NHWC) = (1,5,5,1), ksize,strides = 3  or ksize,strides = 2

In [9]:
print("[Pooling Exam2] Input shape(NHWC) = (1,5,5,1), ksize,strides = 3  or ksize,strides = 2")

np_input = np.arange(1,26,1,dtype=np.float32).reshape(1,5,5,1)

Print_Array(np_input, "Input")

input_constant = tf.constant(np_input)

pool_3 = tf.nn.max_pool2d(input_constant,ksize=3,strides=3,padding="VALID")
pool_2 = tf.nn.max_pool2d(input_constant,ksize=2,strides=2,padding="VALID")

with tf.Session() as sess:
  out_3,out_2 = sess.run((pool_3, pool_2))
  Print_Array(out_3, "Output : ksize = 3, strides = 3")
  Print_Array(out_2, "Output : ksize = 2, strides = 2")

[Pooling Exam2] Input shape(NHWC) = (1,5,5,1), ksize,strides = 3  or ksize,strides = 2
Shape of Input : (1, 5, 5, 1)
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]
   [ 5.]]

  [[ 6.]
   [ 7.]
   [ 8.]
   [ 9.]
   [10.]]

  [[11.]
   [12.]
   [13.]
   [14.]
   [15.]]

  [[16.]
   [17.]
   [18.]
   [19.]
   [20.]]

  [[21.]
   [22.]
   [23.]
   [24.]
   [25.]]]]
Shape of Output : ksize = 3, strides = 3 : (1, 1, 1, 1)
[[[[13.]]]]
Shape of Output : ksize = 2, strides = 2 : (1, 2, 2, 1)
[[[[ 7.]
   [ 9.]]

  [[17.]
   [19.]]]]
