<a href="https://colab.research.google.com/github/KwonYN/TIL/blob/master/PYTHON/TENSORFLOW/Ch5_%EC%98%88%EC%A0%9C_01_Basic_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter5-2. Basic RNN

### [예제1] Basic RNN

> ### Load Module

In [1]:
%tensorflow_version 1.x

import numpy as np
import tensorflow as tf

print("Module Loaded.")
print("NumPy Version :{}".format(np.__version__))
print("TensorFlow Version :{}".format(tf.__version__))

tf.VariableScope.reuse = tf.AUTO_REUSE

Module Loaded.
NumPy Version :1.17.4
TensorFlow Version :1.15.0


> ### One to One
> #### Input dim = 4 -> hidden_size = 3

In [3]:
hidden_size = 3
input_dim = 4

x_data = np.array([[[1,0,0,0]]], dtype=np.float32)
x_ph = tf.placeholder(dtype=tf.float32, shape=(None,1,input_dim))

cell_1 = tf.nn.rnn_cell.BasicRNNCell(num_units = hidden_size)
output_1, _states_1 = tf.nn.dynamic_rnn(cell_1, x_ph, dtype=tf.float32)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  out = sess.run(output_1, feed_dict = {x_ph:x_data})

print("Shape of out : {}".format(out.shape))
print(out)

Shape of out : (1, 1, 3)
[[[0.4713394  0.47270626 0.29054242]]]


> ### Multi to Multi
> #### Input dim = 4 -> hidden_size = 2, sequence_length = 5

In [5]:
hidden_size = 3
input_dim = 4
sequence_length = 5

x_data = np.array([[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,1,0],[0,0,0,1]]], dtype=np.float32)
print("Shape of input :", x_data.shape)
x_ph = tf.placeholder(dtype=tf.float32, shape=(None, sequence_length, input_dim))

cell_2 = tf.nn.rnn_cell.BasicRNNCell(num_units = hidden_size)
output_2, _states_2 = tf.nn.dynamic_rnn(cell_2, x_ph, dtype=tf.float32)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  out = sess.run(output_2, feed_dict = {x_ph:x_data})

print("Shape of out : {}".format(out.shape))
print(out)

Shape of input : (1, 5, 4)
Shape of out : (1, 5, 3)
[[[ 0.63723516  0.17438263 -0.5689401 ]
  [ 0.60229737  0.6790457  -0.42140174]
  [-0.25152624  0.25003612  0.05267095]
  [-0.38596103 -0.5442432  -0.38445002]
  [ 0.35177314 -0.54134905 -0.52894247]]]


> ### Batch Multi to Multi
> #### Input dim = 4 -> hidden_size = 2, sequence_length = 5

In [6]:
hidden_size = 3
input_dim = 4
sequence_length = 5

hot_encoding = {'h':[1,0,0,0],'e':[0,1,0,0],'l':[0,0,1,0],'o':[0,0,0,1]}
x_data = np.array([['h','e','l','l','o'],['h','e','l','l','o'],['h','e','l','l','o']])
x_shape = x_data.shape
print("x_shape :", x_shape)

x_data = x_data.reshape((-1))
print("x_data :", x_data)
x_data_onehot = np.array([hot_encoding[x_elem] for x_elem in x_data]).reshape((*x_shape,4))

x_ph = tf.placeholder(dtype=tf.float32, shape=(None, sequence_length, input_dim))

cell_3 = tf.nn.rnn_cell.BasicRNNCell(num_units = hidden_size)
output_3, _states_3 = tf.nn.dynamic_rnn(cell_3, x_ph, dtype=tf.float32)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  out = sess.run(output_3, feed_dict = {x_ph:x_data_onehot})

print("Shape of out : {}".format(out.shape))
print(out)

x_shape : (3, 5)
x_data : ['h' 'e' 'l' 'l' 'o' 'h' 'e' 'l' 'l' 'o' 'h' 'e' 'l' 'l' 'o']
Shape of out : (3, 5, 3)
[[[ 0.6392374   0.11481747  0.17014639]
  [-0.36236352 -0.5240643   0.45575127]
  [-0.75681484 -0.63229764  0.6236449 ]
  [-0.8349091  -0.60795265  0.6816566 ]
  [-0.29483363 -0.40633473  0.7558709 ]]

 [[ 0.6392374   0.11481747  0.17014639]
  [-0.36236352 -0.5240643   0.45575127]
  [-0.75681484 -0.63229764  0.6236449 ]
  [-0.8349091  -0.60795265  0.6816566 ]
  [-0.29483363 -0.40633473  0.7558709 ]]

 [[ 0.6392374   0.11481747  0.17014639]
  [-0.36236352 -0.5240643   0.45575127]
  [-0.75681484 -0.63229764  0.6236449 ]
  [-0.8349091  -0.60795265  0.6816566 ]
  [-0.29483363 -0.40633473  0.7558709 ]]]
